FROM elixir:1.15.1 as build

ENV MIX_ENV=prod

COPY lib ./lib
COPY mix.exs .
COPY mix.lock .

RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get && \
    mix release

# Copy the production.env.exs file to the container
COPY config/prod.env.exs config/

# Final stage for the production release
FROM alpine:3.14

RUN apk add --no-cache bash openssl

WORKDIR /app

# Copy the release from the build stage
COPY --from=build . .

# Copy the Erlang runtime files
# COPY --from=build /app/_build/prod/rel/todo_app/erts-* /app/erts/

# Set the environment variables
ENV REPLACE_OS_VARS=true
ENV PORT=80
ENV MIX_ENV=prod

EXPOSE 80

# CMD ["ls", "_build/prod/rel/todo_app/erts-14.0.2/bin"]
CMD ["_build/prod/rel/todo_app/bin/todo_app", "start"]
